## Set global build ENV
ARG NODEJS_VERSION="22"

## Base image for all building stages
FROM node:${NODEJS_VERSION}-slim AS base

ARG USE_CN_MIRROR

ENV DEBIAN_FRONTEND="noninteractive"

RUN \
    # If you want to build docker in China, build with --build-arg USE_CN_MIRROR=true
    if [ "${USE_CN_MIRROR:-false}" = "true" ]; then \
        sed -i "s/deb.debian.org/mirrors.ustc.edu.cn/g" "/etc/apt/sources.list.d/debian.sources"; \
    fi \
    # Add required package
    && apt update \
    && apt install ca-certificates proxychains-ng -qy \
    # Prepare required package to distroless
    && mkdir -p /distroless/bin /distroless/etc /distroless/etc/ssl/certs /distroless/lib \
    # Copy proxychains to distroless
    && cp /usr/lib/$(arch)-linux-gnu/libproxychains.so.4 /distroless/lib/libproxychains.so.4 \
    && cp /usr/lib/$(arch)-linux-gnu/libdl.so.2 /distroless/lib/libdl.so.2 \
    && cp /usr/bin/proxychains4 /distroless/bin/proxychains \
    && cp /etc/proxychains4.conf /distroless/etc/proxychains4.conf \
    # Copy node to distroless
    && cp /usr/lib/$(arch)-linux-gnu/libstdc++.so.6 /distroless/lib/libstdc++.so.6 \
    && cp /usr/lib/$(arch)-linux-gnu/libgcc_s.so.1 /distroless/lib/libgcc_s.so.1 \
    && cp /usr/local/bin/node /distroless/bin/node \
    # Copy CA certificates to distroless
    && cp /etc/ssl/certs/ca-certificates.crt /distroless/etc/ssl/certs/ca-certificates.crt \
    # Cleanup temp files
    && rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

## Builder image, install all the dependencies and build the app
FROM base AS builder

ARG USE_CN_MIRROR
ARG NEXT_PUBLIC_BASE_PATH
ARG NEXT_PUBLIC_SENTRY_DSN
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ARG NEXT_PUBLIC_ANALYTICS_POSTHOG
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_ANALYTICS_UMAMI
ARG NEXT_PUBLIC_UMAMI_SCRIPT_URL
ARG NEXT_PUBLIC_UMAMI_WEBSITE_ID
ARG FEATURE_FLAGS
ARG CLERK_PUBLISHABLE_KEY
ARG CLERK_SECRET_KEY
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG CLERK_WEBHOOK_SECRET
ARG CLERK_SIGN_IN_URL
ARG CLERK_SIGN_UP_URL
ARG CLERK_AFTER_SIGN_IN_URL
ARG CLERK_AFTER_SIGN_UP_URL
ARG NEXT_PUBLIC_ENABLE_CLERK_AUTH
ARG NEXT_PUBLIC_ENABLE_NEXT_AUTH
ARG NEXT_AUTH_SECRET
ARG NEXT_AUTH_SSO_PROVIDERS
ARG AUTH_AUTH0_ID
ARG AUTH_AUTH0_SECRET
ARG AUTH_AUTH0_ISSUER
ARG AUTH_GOOGLE_ID
ARG AUTH_GOOGLE_SECRET
ARG AUTH_GITHUB_ID
ARG AUTH_GITHUB_SECRET
ARG AUTH_MICROSOFT_ENTRA_ID_ID
ARG AUTH_MICROSOFT_ENTRA_ID_SECRET
ARG AUTH_MICROSOFT_ENTRA_ID_TENANT_ID
ARG AUTH_AUTHENTIK_ID
ARG AUTH_AUTHENTIK_SECRET
ARG AUTH_AUTHENTIK_ISSUER
ARG AUTH_ZITADEL_ID
ARG AUTH_ZITADEL_SECRET
ARG AUTH_ZITADEL_ISSUER
ARG KEY_VAULTS_SECRET
ARG DATABASE_TEST_URL
ARG DISABLE_REMOVE_GLOBAL_FILE
ARG NEXT_PUBLIC_ENABLED_SERVER_SERVICE
ARG NEXT_PUBLIC_SERVICE_MODE
ARG S3_ACCESS_KEY_ID
ARG S3_SECRET_ACCESS_KEY
ARG S3_ENDPOINT
ARG S3_BUCKET
ARG S3_REGION
ARG S3_PUBLIC_DOMAIN
ARG S3_ENABLE_PATH_STYLE
ARG S3_PREVIEW_URL_EXPIRE_IN
ARG S3_SET_ACL
ARG NEXT_PUBLIC_S3_DOMAIN
ARG NEXT_PUBLIC_S3_FILE_PATH
ARG DEFAULT_FILES_CONFIG
ARG FILE_TYPE_CHUNKING_RULES
ARG UNSTRUCTURED_API_KEY
ARG UNSTRUCTURED_SERVER_URL
ARG CHUNKS_AUTO_EMBEDDING
ARG CHUNKS_AUTO_GEN_METADATA
ARG CRAWLER_IMPLS
ARG SEARCH_PROVIDERS
ARG SEARXNG_URL
ARG APP_URL
ARG VERCEL_EDGE_CONFIG
ARG ENABLE_AUTH_PROTECTION
ARG CDN_USE_GLOBAL
ARG CUSTOM_FONT_FAMILY
ARG CUSTOM_FONT_URL
ARG SSRF_ALLOW_PRIVATE_IP_ADDRESS
ARG SSRF_ALLOW_IP_ADDRESS_LIST
ARG RESEND_API_KEY
ARG RESEND_SENDER
ARG AGENTS_INDEX_URL
ARG PLUGINS_INDEX_URL
ARG PLUGIN_SETTINGS
ARG NEXT_PUBLIC_ENABLE_SENTRY
ARG ENABLED_OPENAI
ARG ENABLED_AZURE_OPENAI
ARG ENABLED_AZUREAI
ARG ENABLED_ZHIPU
ARG ENABLED_DEEPSEEK
ARG ENABLED_GOOGLE
ARG ENABLED_MOONSHOT
ARG ENABLED_PERPLEXITY
ARG ENABLED_ANTHROPIC
ARG ENABLED_MINIMAX
ARG ENABLED_MISTRAL
ARG ENABLED_GROQ
ARG ENABLED_GITHUB
ARG ENABLED_OPENROUTER
ARG ENABLED_ZEROONE
ARG ENABLED_TOGETHERAI
ARG ENABLED_FIREWORKSAI
ARG ENABLED_AWS_BEDROCK
ARG ENABLED_OLLAMA
ARG ENABLED_BAICHUAN
ARG ENABLED_AI360
ARG ENABLED_AI21
ARG ENABLED_CLOUDFLARE
ARG ENABLED_COHERE
ARG ENABLED_HUGGINGFACE
ARG ENABLED_HUNYUAN
ARG ENABLED_INTERNLM
ARG ENABLED_JINA
ARG ENABLED_MODELSCOPE
ARG ENABLED_NOVITA
ARG ENABLED_NVIDIA
ARG ENABLED_QINIU
ARG ENABLED_QWEN
ARG ENABLED_SAMBANOVA
ARG ENABLED_SENSENOVA
ARG ENABLED_SILICONCLOUD
ARG ENABLED_SPARK
ARG ENABLED_STEPFUN
ARG ENABLED_TAICHU
ARG ENABLED_UPSTAGE
ARG ENABLED_V0
ARG ENABLED_VLLM
ARG ENABLED_WENXIN
ARG ENABLED_XAI
ARG ENABLED_XINFERENCE
ARG ENABLED_TENCENT_CLOUD
ARG ENABLED_INFINIAI
ARG ENABLED_HIGRESS
ARG ENABLED_GITEE_AI
ARG NEXT_PUBLIC_WEBSOCKET_URL
ARG API_URL
ARG REDIS_SESSION_TTL
ARG REDIS_SESSION_SYNC_INTERVAL
ARG REDIS_SESSION_MAX_MESSAGES
ARG DB_SYNC_BATCH_SIZE
ARG DB_SYNC_RETRY_ATTEMPTS
ARG DB_SYNC_RETRY_DELAY
ARG REDIS_SESSION_COMPRESSION
ARG ENABLE_SESSION_METRICS
ARG METRICS_COLLECTION_INTERVAL
ARG REDIS_MODE
ARG STRIPE_SECRET_KEY
ARG STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG STRIPE_ADDITIONAL_USER_MONTHLY_PRICE_ID
ARG STRIPE_ADDITIONAL_USER_YEARLY_PRICE_ID
ARG STRIPE_PRO_PRICE_ID
ARG STRIPE_ENTERPRISE_PRICE_ID
ARG STRIPE_ANNUAL_PRICE_ID
ARG STRIPE_MONTHLY_PRICE_ID
ARG NODE_ENV
ARG DOCKER
ARG NEXT_PUBLIC_IS_DESKTOP_APP
ARG REACT_SCAN_MONITOR_API_KEY
ARG NEXT_PUBLIC_CLIENT_DB
ARG ANALYZE
ARG VERCEL
ARG VERCEL_URL
ARG VOLCENGINE_API_KEY
ARG ENABLED_VOLCENGINE
ARG AWS_SESSION_TOKEN
ARG OLLAMA_PROXY_URL
ARG VLLM_PROXY_URL
ARG XINFERENCE_PROXY_URL
ARG QINIU_PROXY_URL
ARG QWEN_PROXY_URL
ARG STEPFUN_PROXY_URL
ARG NOVITA_PROXY_URL
ARG NVIDIA_PROXY_URL
ARG BAICHUAN_PROXY_URL
ARG TAICHU_PROXY_URL
ARG CLOUDFLARE_PROXY_URL
ARG AI360_PROXY_URL
ARG SILICONCLOUD_PROXY_URL
ARG GITEE_AI_PROXY_URL
ARG UPSTAGE_PROXY_URL
ARG SPARK_PROXY_URL
ARG SPARK_SEARCH_MODE
ARG HUNYUAN_PROXY_URL
ARG INTERNLM_PROXY_URL
ARG JINA_PROXY_URL
ARG MODELSCOPE_PROXY_URL
ARG SAMBANOVA_PROXY_URL
ARG SENSENOVA_PROXY_URL
ARG TOGETHERAI_PROXY_URL
ARG V0_PROXY_URL
ARG WENXIN_PROXY_URL
ARG XAI_PROXY_URL
ARG TENCENT_CLOUD_PROXY_URL
ARG INFINIAI_PROXY_URL
ARG HIGRESS_PROXY_URL
ARG HUGGINGFACE_PROXY_URL
ARG COHERE_PROXY_URL
ARG ANTHROPIC_PROXY_URL
ARG GOOGLE_PROXY_URL
ARG GROQ_PROXY_URL
ARG OPENAI_PROXY_URL
ARG PERPLEXITY_PROXY_URL
ARG MOONSHOT_PROXY_URL
ARG DEEPSEEK_PROXY_URL
ARG ZHIPU_PROXY_URL
ARG AZURE_PROXY_URL
ARG AZUREAI_PROXY_URL
ARG AWS_BEDROCK_PROXY_URL
ARG AI21_PROXY_URL

ENV NEXT_PUBLIC_BASE_PATH="${NEXT_PUBLIC_BASE_PATH}" \
    FEATURE_FLAGS="${FEATURE_FLAGS}"

# Sentry
ENV NEXT_PUBLIC_SENTRY_DSN="${NEXT_PUBLIC_SENTRY_DSN}" \
    SENTRY_ORG="${SENTRY_ORG}" \
    SENTRY_PROJECT="${SENTRY_PROJECT}"

# Posthog
ENV NEXT_PUBLIC_ANALYTICS_POSTHOG="${NEXT_PUBLIC_ANALYTICS_POSTHOG}" \
    NEXT_PUBLIC_POSTHOG_HOST="${NEXT_PUBLIC_POSTHOG_HOST}" \
    NEXT_PUBLIC_POSTHOG_KEY="${NEXT_PUBLIC_POSTHOG_KEY}"

# Umami
ENV NEXT_PUBLIC_ANALYTICS_UMAMI="${NEXT_PUBLIC_ANALYTICS_UMAMI}" \
    NEXT_PUBLIC_UMAMI_SCRIPT_URL="${NEXT_PUBLIC_UMAMI_SCRIPT_URL}" \
    NEXT_PUBLIC_UMAMI_WEBSITE_ID="${NEXT_PUBLIC_UMAMI_WEBSITE_ID}"

# Node
ENV NODE_OPTIONS="--max-old-space-size=8192"

WORKDIR /app

COPY package.json pnpm-workspace.yaml ./
COPY .npmrc ./
COPY packages ./packages

RUN \
    # If you want to build docker in China, build with --build-arg USE_CN_MIRROR=true
    if [ "${USE_CN_MIRROR:-false}" = "true" ]; then \
        export SENTRYCLI_CDNURL="https://npmmirror.com/mirrors/sentry-cli"; \
        npm config set registry "https://registry.npmmirror.com/"; \
        echo 'canvas_binary_host_mirror=https://npmmirror.com/mirrors/canvas' >> .npmrc; \
    fi \
    # Set the registry for corepack
    && export COREPACK_NPM_REGISTRY=$(npm config get registry | sed 's/\/$//') \
    # Update corepack to latest (nodejs/corepack#612)
    && npm i -g corepack@latest \
    # Enable corepack
    && corepack enable \
    # Use pnpm for corepack
    && corepack use $(sed -n 's/.*"packageManager": "\(.*\)".*/\1/p' package.json) \
    # Install the dependencies
    && pnpm i

COPY . .

# run build standalone for docker version
RUN npm run build:docker

## Application image, copy all the files for production
FROM busybox:latest AS app

COPY --from=base /distroless/ /

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder /app/.next/standalone /app/

# Copy server launcher
COPY --from=builder /app/scripts/serverLauncher/startServer.js /app/startServer.js

RUN \
    # Add nextjs:nodejs to run the app
    addgroup -S -g 1001 nodejs \
    && adduser -D -G nodejs -H -S -h /app -u 1001 nextjs \
    # Set permission for nextjs:nodejs
    && chown -R nextjs:nodejs /app /etc/proxychains4.conf

## Production image, copy all the files and run next
FROM scratch

# Copy all the files from app, set the correct permission for prerender cache
COPY --from=app / /

ENV NODE_ENV="production" \
    NODE_OPTIONS="--dns-result-order=ipv4first --use-openssl-ca" \
    NODE_EXTRA_CA_CERTS="" \
    NODE_TLS_REJECT_UNAUTHORIZED="" \
    SSL_CERT_DIR="/etc/ssl/certs/ca-certificates.crt"

# Make the middleware rewrite through local as default
# refs: https://github.com/lobehub/lobe-chat/issues/5876
ENV MIDDLEWARE_REWRITE_THROUGH_LOCAL="1"

# set hostname to localhost
ENV HOSTNAME="0.0.0.0" \
    PORT="3210"

# General Variables
ENV ACCESS_CODE="${ACCESS_CODE}" \
    API_KEY_SELECT_MODE="${API_KEY_SELECT_MODE}" \
    DEFAULT_AGENT_CONFIG="${DEFAULT_AGENT_CONFIG}" \
    SYSTEM_AGENT="${SYSTEM_AGENT}" \
    FEATURE_FLAGS="${FEATURE_FLAGS}" \
    PROXY_URL="${PROXY_URL}" \
    DATABASE_DRIVER="${DATABASE_DRIVER}" \
    DATABASE_URL="${DATABASE_URL}" \
    REDIS_URL="${REDIS_URL}" \
    UPSTASH_REDIS_REST_URL="${UPSTASH_REDIS_REST_URL}" \
    UPSTASH_REDIS_REST_TOKEN="${UPSTASH_REDIS_REST_TOKEN}" \
    NEXTAUTH_SECRET="${NEXTAUTH_SECRET}" \
    NEXTAUTH_URL="${NEXTAUTH_URL}" \
    NEXT_PUBLIC_BASE_PATH="${NEXT_PUBLIC_BASE_PATH}" \
    NEXT_PUBLIC_SENTRY_DSN="${NEXT_PUBLIC_SENTRY_DSN}" \
    NEXT_PUBLIC_ANALYTICS_POSTHOG="${NEXT_PUBLIC_ANALYTICS_POSTHOG}" \
    NEXT_PUBLIC_POSTHOG_HOST="${NEXT_PUBLIC_POSTHOG_HOST}" \
    NEXT_PUBLIC_POSTHOG_KEY="${NEXT_PUBLIC_POSTHOG_KEY}" \
    NEXT_PUBLIC_ANALYTICS_UMAMI="${NEXT_PUBLIC_ANALYTICS_UMAMI}" \
    NEXT_PUBLIC_UMAMI_SCRIPT_URL="${NEXT_PUBLIC_UMAMI_SCRIPT_URL}" \
    NEXT_PUBLIC_UMAMI_WEBSITE_ID="${NEXT_PUBLIC_UMAMI_WEBSITE_ID}" \
    CLERK_PUBLISHABLE_KEY="${CLERK_PUBLISHABLE_KEY}" \
    CLERK_SECRET_KEY="${CLERK_SECRET_KEY}" \
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}" \
    CLERK_WEBHOOK_SECRET="${CLERK_WEBHOOK_SECRET}" \
    CLERK_SIGN_IN_URL="${CLERK_SIGN_IN_URL}" \
    CLERK_SIGN_UP_URL="${CLERK_SIGN_UP_URL}" \
    CLERK_AFTER_SIGN_IN_URL="${CLERK_AFTER_SIGN_IN_URL}" \
    CLERK_AFTER_SIGN_UP_URL="${CLERK_AFTER_SIGN_UP_URL}" \
    NEXT_PUBLIC_ENABLE_CLERK_AUTH="${NEXT_PUBLIC_ENABLE_CLERK_AUTH}" \
    NEXT_PUBLIC_ENABLE_NEXT_AUTH="${NEXT_PUBLIC_ENABLE_NEXT_AUTH}" \
    NEXT_AUTH_SECRET="${NEXT_AUTH_SECRET}" \
    NEXT_AUTH_SSO_PROVIDERS="${NEXT_AUTH_SSO_PROVIDERS}" \
    AUTH_AUTH0_ID="${AUTH_AUTH0_ID}" \
    AUTH_AUTH0_SECRET="${AUTH_AUTH0_SECRET}" \
    AUTH_AUTH0_ISSUER="${AUTH_AUTH0_ISSUER}" \
    AUTH_GOOGLE_ID="${AUTH_GOOGLE_ID}" \
    AUTH_GOOGLE_SECRET="${AUTH_GOOGLE_SECRET}" \
    AUTH_GITHUB_ID="${AUTH_GITHUB_ID}" \
    AUTH_GITHUB_SECRET="${AUTH_GITHUB_SECRET}" \
    AUTH_MICROSOFT_ENTRA_ID_ID="${AUTH_MICROSOFT_ENTRA_ID_ID}" \
    AUTH_MICROSOFT_ENTRA_ID_SECRET="${AUTH_MICROSOFT_ENTRA_ID_SECRET}" \
    AUTH_MICROSOFT_ENTRA_ID_TENANT_ID="${AUTH_MICROSOFT_ENTRA_ID_TENANT_ID}" \
    AUTH_AUTHENTIK_ID="${AUTH_AUTHENTIK_ID}" \
    AUTH_AUTHENTIK_SECRET="${AUTH_AUTHENTIK_SECRET}" \
    AUTH_AUTHENTIK_ISSUER="${AUTH_AUTHENTIK_ISSUER}" \
    AUTH_ZITADEL_ID="${AUTH_ZITADEL_ID}" \
    AUTH_ZITADEL_SECRET="${AUTH_ZITADEL_SECRET}" \
    AUTH_ZITADEL_ISSUER="${AUTH_ZITADEL_ISSUER}"

# Database & Storage Variables
ENV \
    KEY_VAULTS_SECRET="${KEY_VAULTS_SECRET}" \
    DATABASE_TEST_URL="${DATABASE_TEST_URL}" \
    DISABLE_REMOVE_GLOBAL_FILE="${DISABLE_REMOVE_GLOBAL_FILE}" \
    NEXT_PUBLIC_ENABLED_SERVER_SERVICE="${NEXT_PUBLIC_ENABLED_SERVER_SERVICE}" \
    NEXT_PUBLIC_SERVICE_MODE="${NEXT_PUBLIC_SERVICE_MODE}" \
    S3_ACCESS_KEY_ID="${S3_ACCESS_KEY_ID}" \
    S3_SECRET_ACCESS_KEY="${S3_SECRET_ACCESS_KEY}" \
    S3_ENDPOINT="${S3_ENDPOINT}" \
    S3_BUCKET="${S3_BUCKET}" \
    S3_REGION="${S3_REGION}" \
    S3_PUBLIC_DOMAIN="${S3_PUBLIC_DOMAIN}" \
    S3_ENABLE_PATH_STYLE="${S3_ENABLE_PATH_STYLE}" \
    S3_PREVIEW_URL_EXPIRE_IN="${S3_PREVIEW_URL_EXPIRE_IN}" \
    S3_SET_ACL="${S3_SET_ACL}" \
    NEXT_PUBLIC_S3_DOMAIN="${NEXT_PUBLIC_S3_DOMAIN}" \
    NEXT_PUBLIC_S3_FILE_PATH="${NEXT_PUBLIC_S3_FILE_PATH}"

# Knowledge & File Processing Variables
ENV \
    DEFAULT_FILES_CONFIG="${DEFAULT_FILES_CONFIG}" \
    FILE_TYPE_CHUNKING_RULES="${FILE_TYPE_CHUNKING_RULES}" \
    UNSTRUCTURED_API_KEY="${UNSTRUCTURED_API_KEY}" \
    UNSTRUCTURED_SERVER_URL="${UNSTRUCTURED_SERVER_URL}" \
    CHUNKS_AUTO_EMBEDDING="${CHUNKS_AUTO_EMBEDDING}" \
    CHUNKS_AUTO_GEN_METADATA="${CHUNKS_AUTO_GEN_METADATA}"

# Tools & Search Variables
ENV \
    CRAWLER_IMPLS="${CRAWLER_IMPLS}" \
    SEARCH_PROVIDERS="${SEARCH_PROVIDERS}" \
    SEARXNG_URL="${SEARXNG_URL}"

# App Configuration Variables
ENV \
    APP_URL="${APP_URL}" \
    VERCEL_EDGE_CONFIG="${VERCEL_EDGE_CONFIG}" \
    ENABLE_AUTH_PROTECTION="${ENABLE_AUTH_PROTECTION}" \
    CDN_USE_GLOBAL="${CDN_USE_GLOBAL}" \
    CUSTOM_FONT_FAMILY="${CUSTOM_FONT_FAMILY}" \
    CUSTOM_FONT_URL="${CUSTOM_FONT_URL}" \
    SSRF_ALLOW_PRIVATE_IP_ADDRESS="${SSRF_ALLOW_PRIVATE_IP_ADDRESS}" \
    SSRF_ALLOW_IP_ADDRESS_LIST="${SSRF_ALLOW_IP_ADDRESS_LIST}" \
    RESEND_API_KEY="${RESEND_API_KEY}" \
    RESEND_SENDER="${RESEND_SENDER}" \
    AGENTS_INDEX_URL="${AGENTS_INDEX_URL}" \
    PLUGINS_INDEX_URL="${PLUGINS_INDEX_URL}" \
    PLUGIN_SETTINGS="${PLUGIN_SETTINGS}" \
    NEXT_PUBLIC_ENABLE_SENTRY="${NEXT_PUBLIC_ENABLE_SENTRY}"

# LLM Provider Enable/Disable Flags
ENV \
    ENABLED_OPENAI="${ENABLED_OPENAI}" \
    ENABLED_AZURE_OPENAI="${ENABLED_AZURE_OPENAI}" \
    ENABLED_AZUREAI="${ENABLED_AZUREAI}" \
    ENABLED_ZHIPU="${ENABLED_ZHIPU}" \
    ENABLED_DEEPSEEK="${ENABLED_DEEPSEEK}" \
    ENABLED_GOOGLE="${ENABLED_GOOGLE}" \
    ENABLED_MOONSHOT="${ENABLED_MOONSHOT}" \
    ENABLED_PERPLEXITY="${ENABLED_PERPLEXITY}" \
    ENABLED_ANTHROPIC="${ENABLED_ANTHROPIC}" \
    ENABLED_MINIMAX="${ENABLED_MINIMAX}" \
    ENABLED_MISTRAL="${ENABLED_MISTRAL}" \
    ENABLED_GROQ="${ENABLED_GROQ}" \
    ENABLED_GITHUB="${ENABLED_GITHUB}" \
    ENABLED_OPENROUTER="${ENABLED_OPENROUTER}" \
    ENABLED_ZEROONE="${ENABLED_ZEROONE}" \
    ENABLED_TOGETHERAI="${ENABLED_TOGETHERAI}" \
    ENABLED_FIREWORKSAI="${ENABLED_FIREWORKSAI}" \
    ENABLED_AWS_BEDROCK="${ENABLED_AWS_BEDROCK}" \
    ENABLED_OLLAMA="${ENABLED_OLLAMA}" \
    ENABLED_BAICHUAN="${ENABLED_BAICHUAN}" \
    ENABLED_AI360="${ENABLED_AI360}" \
    ENABLED_AI21="${ENABLED_AI21}" \
    ENABLED_CLOUDFLARE="${ENABLED_CLOUDFLARE}" \
    ENABLED_COHERE="${ENABLED_COHERE}" \
    ENABLED_HUGGINGFACE="${ENABLED_HUGGINGFACE}" \
    ENABLED_HUNYUAN="${ENABLED_HUNYUAN}" \
    ENABLED_INTERNLM="${ENABLED_INTERNLM}" \
    ENABLED_JINA="${ENABLED_JINA}" \
    ENABLED_MODELSCOPE="${ENABLED_MODELSCOPE}" \
    ENABLED_NOVITA="${ENABLED_NOVITA}" \
    ENABLED_NVIDIA="${ENABLED_NVIDIA}" \
    ENABLED_QINIU="${ENABLED_QINIU}" \
    ENABLED_QWEN="${ENABLED_QWEN}" \
    ENABLED_SAMBANOVA="${ENABLED_SAMBANOVA}" \
    ENABLED_SENSENOVA="${ENABLED_SENSENOVA}" \
    ENABLED_SILICONCLOUD="${ENABLED_SILICONCLOUD}" \
    ENABLED_SPARK="${ENABLED_SPARK}" \
    ENABLED_STEPFUN="${ENABLED_STEPFUN}" \
    ENABLED_TAICHU="${ENABLED_TAICHU}" \
    ENABLED_UPSTAGE="${ENABLED_UPSTAGE}" \
    ENABLED_V0="${ENABLED_V0}" \
    ENABLED_VLLM="${ENABLED_VLLM}" \
    ENABLED_WENXIN="${ENABLED_WENXIN}" \
    ENABLED_XAI="${ENABLED_XAI}" \
    ENABLED_XINFERENCE="${ENABLED_XINFERENCE}" \
    ENABLED_TENCENT_CLOUD="${ENABLED_TENCENT_CLOUD}" \
    ENABLED_INFINIAI="${ENABLED_INFINIAI}" \
    ENABLED_HIGRESS="${ENABLED_HIGRESS}" \
    ENABLED_GITEE_AI="${ENABLED_GITEE_AI}"

# WebSocket & Redis Session Variables
ENV \
    NEXT_PUBLIC_WEBSOCKET_URL="${NEXT_PUBLIC_WEBSOCKET_URL}" \
    API_URL="${API_URL}" \
    REDIS_SESSION_TTL="${REDIS_SESSION_TTL}" \
    REDIS_SESSION_SYNC_INTERVAL="${REDIS_SESSION_SYNC_INTERVAL}" \
    REDIS_SESSION_MAX_MESSAGES="${REDIS_SESSION_MAX_MESSAGES}" \
    DB_SYNC_BATCH_SIZE="${DB_SYNC_BATCH_SIZE}" \
    DB_SYNC_RETRY_ATTEMPTS="${DB_SYNC_RETRY_ATTEMPTS}" \
    DB_SYNC_RETRY_DELAY="${DB_SYNC_RETRY_DELAY}" \
    REDIS_SESSION_COMPRESSION="${REDIS_SESSION_COMPRESSION}" \
    ENABLE_SESSION_METRICS="${ENABLE_SESSION_METRICS}" \
    METRICS_COLLECTION_INTERVAL="${METRICS_COLLECTION_INTERVAL}" \
    REDIS_MODE="${REDIS_MODE}"

# Stripe & Payment Variables
ENV \
    STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY}" \
    STRIPE_PUBLISHABLE_KEY="${STRIPE_PUBLISHABLE_KEY}" \
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}" \
    STRIPE_WEBHOOK_SECRET="${STRIPE_WEBHOOK_SECRET}" \
    STRIPE_ADDITIONAL_USER_MONTHLY_PRICE_ID="${STRIPE_ADDITIONAL_USER_MONTHLY_PRICE_ID}" \
    STRIPE_ADDITIONAL_USER_YEARLY_PRICE_ID="${STRIPE_ADDITIONAL_USER_YEARLY_PRICE_ID}" \
    STRIPE_PRO_PRICE_ID="${STRIPE_PRO_PRICE_ID}" \
    STRIPE_ENTERPRISE_PRICE_ID="${STRIPE_ENTERPRISE_PRICE_ID}" \
    STRIPE_ANNUAL_PRICE_ID="${STRIPE_ANNUAL_PRICE_ID}" \
    STRIPE_MONTHLY_PRICE_ID="${STRIPE_MONTHLY_PRICE_ID}"

# Build & Development Variables
ENV \
    NODE_ENV="${NODE_ENV}" \
    DOCKER="${DOCKER}" \
    NEXT_PUBLIC_IS_DESKTOP_APP="${NEXT_PUBLIC_IS_DESKTOP_APP}" \
    REACT_SCAN_MONITOR_API_KEY="${REACT_SCAN_MONITOR_API_KEY}" \
    NEXT_PUBLIC_CLIENT_DB="${NEXT_PUBLIC_CLIENT_DB}" \
    ANALYZE="${ANALYZE}" \
    VERCEL="${VERCEL}" \
    VERCEL_URL="${VERCEL_URL}"

# Additional LLM Provider Variables
ENV \
    VOLCENGINE_API_KEY="${VOLCENGINE_API_KEY}" \
    ENABLED_VOLCENGINE="${ENABLED_VOLCENGINE}" \
    AWS_SESSION_TOKEN="${AWS_SESSION_TOKEN}" \
    OLLAMA_PROXY_URL="${OLLAMA_PROXY_URL}" \
    VLLM_PROXY_URL="${VLLM_PROXY_URL}" \
    XINFERENCE_PROXY_URL="${XINFERENCE_PROXY_URL}" \
    QINIU_PROXY_URL="${QINIU_PROXY_URL}" \
    QWEN_PROXY_URL="${QWEN_PROXY_URL}" \
    STEPFUN_PROXY_URL="${STEPFUN_PROXY_URL}" \
    NOVITA_PROXY_URL="${NOVITA_PROXY_URL}" \
    NVIDIA_PROXY_URL="${NVIDIA_PROXY_URL}" \
    BAICHUAN_PROXY_URL="${BAICHUAN_PROXY_URL}" \
    TAICHU_PROXY_URL="${TAICHU_PROXY_URL}" \
    CLOUDFLARE_PROXY_URL="${CLOUDFLARE_PROXY_URL}" \
    AI360_PROXY_URL="${AI360_PROXY_URL}" \
    SILICONCLOUD_PROXY_URL="${SILICONCLOUD_PROXY_URL}" \
    GITEE_AI_PROXY_URL="${GITEE_AI_PROXY_URL}" \
    UPSTAGE_PROXY_URL="${UPSTAGE_PROXY_URL}" \
    SPARK_PROXY_URL="${SPARK_PROXY_URL}" \
    SPARK_SEARCH_MODE="${SPARK_SEARCH_MODE}" \
    HUNYUAN_PROXY_URL="${HUNYUAN_PROXY_URL}" \
    INTERNLM_PROXY_URL="${INTERNLM_PROXY_URL}" \
    JINA_PROXY_URL="${JINA_PROXY_URL}" \
    MODELSCOPE_PROXY_URL="${MODELSCOPE_PROXY_URL}" \
    SAMBANOVA_PROXY_URL="${SAMBANOVA_PROXY_URL}" \
    SENSENOVA_PROXY_URL="${SENSENOVA_PROXY_URL}" \
    TOGETHERAI_PROXY_URL="${TOGETHERAI_PROXY_URL}" \
    V0_PROXY_URL="${V0_PROXY_URL}" \
    WENXIN_PROXY_URL="${WENXIN_PROXY_URL}" \
    XAI_PROXY_URL="${XAI_PROXY_URL}" \
    TENCENT_CLOUD_PROXY_URL="${TENCENT_CLOUD_PROXY_URL}" \
    INFINIAI_PROXY_URL="${INFINIAI_PROXY_URL}" \
    HIGRESS_PROXY_URL="${HIGRESS_PROXY_URL}" \
    GITEE_AI_PROXY_URL="${GITEE_AI_PROXY_URL}" \
    HUGGINGFACE_PROXY_URL="${HUGGINGFACE_PROXY_URL}" \
    COHERE_PROXY_URL="${COHERE_PROXY_URL}" \
    ANTHROPIC_PROXY_URL="${ANTHROPIC_PROXY_URL}" \
    GOOGLE_PROXY_URL="${GOOGLE_PROXY_URL}" \
    GROQ_PROXY_URL="${GROQ_PROXY_URL}" \
    OPENAI_PROXY_URL="${OPENAI_PROXY_URL}" \
    PERPLEXITY_PROXY_URL="${PERPLEXITY_PROXY_URL}" \
    MOONSHOT_PROXY_URL="${MOONSHOT_PROXY_URL}" \
    DEEPSEEK_PROXY_URL="${DEEPSEEK_PROXY_URL}" \
    ZHIPU_PROXY_URL="${ZHIPU_PROXY_URL}" \
    AZURE_PROXY_URL="${AZURE_PROXY_URL}" \
    AZUREAI_PROXY_URL="${AZUREAI_PROXY_URL}" \
    AWS_BEDROCK_PROXY_URL="${AWS_BEDROCK_PROXY_URL}" \
    AI21_PROXY_URL="${AI21_PROXY_URL}"

# Model Variables
ENV \
    # AI21
    AI21_API_KEY="${AI21_API_KEY}" AI21_MODEL_LIST="${AI21_MODEL_LIST}" \
    # Ai360
    AI360_API_KEY="${AI360_API_KEY}" AI360_MODEL_LIST="${AI360_MODEL_LIST}" \
    # Anthropic
    ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}" ANTHROPIC_MODEL_LIST="${ANTHROPIC_MODEL_LIST}" ANTHROPIC_PROXY_URL="${ANTHROPIC_PROXY_URL}" \
    # Amazon Bedrock
    AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" AWS_REGION="${AWS_REGION}" AWS_BEDROCK_MODEL_LIST="${AWS_BEDROCK_MODEL_LIST}" \
    # Azure OpenAI
    AZURE_API_KEY="${AZURE_API_KEY}" AZURE_API_VERSION="${AZURE_API_VERSION}" AZURE_ENDPOINT="${AZURE_ENDPOINT}" AZURE_MODEL_LIST="${AZURE_MODEL_LIST}" \
    # Baichuan
    BAICHUAN_API_KEY="${BAICHUAN_API_KEY}" BAICHUAN_MODEL_LIST="${BAICHUAN_MODEL_LIST}" \
    # Cloudflare
    CLOUDFLARE_API_KEY="${CLOUDFLARE_API_KEY}" CLOUDFLARE_BASE_URL_OR_ACCOUNT_ID="${CLOUDFLARE_BASE_URL_OR_ACCOUNT_ID}" CLOUDFLARE_MODEL_LIST="${CLOUDFLARE_MODEL_LIST}" \
    # Cohere
    COHERE_API_KEY="${COHERE_API_KEY}" COHERE_MODEL_LIST="${COHERE_MODEL_LIST}" COHERE_PROXY_URL="${COHERE_PROXY_URL}" \
    # DeepSeek
    DEEPSEEK_API_KEY="${DEEPSEEK_API_KEY}" DEEPSEEK_MODEL_LIST="${DEEPSEEK_MODEL_LIST}" \
    # Fireworks AI
    FIREWORKSAI_API_KEY="${FIREWORKSAI_API_KEY}" FIREWORKSAI_MODEL_LIST="${FIREWORKSAI_MODEL_LIST}" \
    # Gitee AI
    GITEE_AI_API_KEY="${GITEE_AI_API_KEY}" GITEE_AI_MODEL_LIST="${GITEE_AI_MODEL_LIST}" \
    # GitHub
    GITHUB_TOKEN="${GITHUB_TOKEN}" GITHUB_MODEL_LIST="${GITHUB_MODEL_LIST}" \
    # Google
    GOOGLE_API_KEY="${GOOGLE_API_KEY}" GOOGLE_MODEL_LIST="${GOOGLE_MODEL_LIST}" GOOGLE_PROXY_URL="${GOOGLE_PROXY_URL}" \
    # Groq
    GROQ_API_KEY="${GROQ_API_KEY}" GROQ_MODEL_LIST="${GROQ_MODEL_LIST}" GROQ_PROXY_URL="${GROQ_PROXY_URL}" \
    # Higress
    HIGRESS_API_KEY="${HIGRESS_API_KEY}" HIGRESS_MODEL_LIST="${HIGRESS_MODEL_LIST}" HIGRESS_PROXY_URL="${HIGRESS_PROXY_URL}" \
    # HuggingFace
    HUGGINGFACE_API_KEY="${HUGGINGFACE_API_KEY}" HUGGINGFACE_MODEL_LIST="${HUGGINGFACE_MODEL_LIST}" HUGGINGFACE_PROXY_URL="${HUGGINGFACE_PROXY_URL}" \
    # Hunyuan
    HUNYUAN_API_KEY="${HUNYUAN_API_KEY}" HUNYUAN_MODEL_LIST="${HUNYUAN_MODEL_LIST}" \
    # InternLM
    INTERNLM_API_KEY="${INTERNLM_API_KEY}" INTERNLM_MODEL_LIST="${INTERNLM_MODEL_LIST}" \
    # Jina
    JINA_API_KEY="${JINA_API_KEY}" JINA_MODEL_LIST="${JINA_MODEL_LIST}" JINA_PROXY_URL="${JINA_PROXY_URL}" \
    # Minimax
    MINIMAX_API_KEY="${MINIMAX_API_KEY}" MINIMAX_MODEL_LIST="${MINIMAX_MODEL_LIST}" \
    # Mistral
    MISTRAL_API_KEY="${MISTRAL_API_KEY}" MISTRAL_MODEL_LIST="${MISTRAL_MODEL_LIST}" \
    # ModelScope
    MODELSCOPE_API_KEY="${MODELSCOPE_API_KEY}" MODELSCOPE_MODEL_LIST="${MODELSCOPE_MODEL_LIST}" MODELSCOPE_PROXY_URL="${MODELSCOPE_PROXY_URL}" \
    # Moonshot
    MOONSHOT_API_KEY="${MOONSHOT_API_KEY}" MOONSHOT_MODEL_LIST="${MOONSHOT_MODEL_LIST}" MOONSHOT_PROXY_URL="${MOONSHOT_PROXY_URL}" \
    # Novita
    NOVITA_API_KEY="${NOVITA_API_KEY}" NOVITA_MODEL_LIST="${NOVITA_MODEL_LIST}" \
    # Nvidia NIM
    NVIDIA_API_KEY="${NVIDIA_API_KEY}" NVIDIA_MODEL_LIST="${NVIDIA_MODEL_LIST}" NVIDIA_PROXY_URL="${NVIDIA_PROXY_URL}" \
    # Ollama
    ENABLED_OLLAMA="${ENABLED_OLLAMA}" OLLAMA_MODEL_LIST="${OLLAMA_MODEL_LIST}" OLLAMA_PROXY_URL="${OLLAMA_PROXY_URL}" \
    # OpenAI
    OPENAI_API_KEY="${OPENAI_API_KEY}" OPENAI_MODEL_LIST="${OPENAI_MODEL_LIST}" OPENAI_PROXY_URL="${OPENAI_PROXY_URL}" \
    # OpenRouter
    OPENROUTER_API_KEY="${OPENROUTER_API_KEY}" OPENROUTER_MODEL_LIST="${OPENROUTER_MODEL_LIST}" \
    # Perplexity
    PERPLEXITY_API_KEY="${PERPLEXITY_API_KEY}" PERPLEXITY_MODEL_LIST="${PERPLEXITY_MODEL_LIST}" PERPLEXITY_PROXY_URL="${PERPLEXITY_PROXY_URL}" \
    # Qiniu
    QINIU_API_KEY="${QINIU_API_KEY}" QINIU_MODEL_LIST="${QINIU_MODEL_LIST}" QINIU_PROXY_URL="${QINIU_PROXY_URL}" \
    # Qwen
    QWEN_API_KEY="${QWEN_API_KEY}" QWEN_MODEL_LIST="${QWEN_MODEL_LIST}" QWEN_PROXY_URL="${QWEN_PROXY_URL}" \
    # SambaNova
    SAMBANOVA_API_KEY="${SAMBANOVA_API_KEY}" SAMBANOVA_MODEL_LIST="${SAMBANOVA_MODEL_LIST}" \
    # SenseNova
    SENSENOVA_API_KEY="${SENSENOVA_API_KEY}" SENSENOVA_MODEL_LIST="${SENSENOVA_MODEL_LIST}" \
    # SiliconCloud
    SILICONCLOUD_API_KEY="${SILICONCLOUD_API_KEY}" SILICONCLOUD_MODEL_LIST="${SILICONCLOUD_MODEL_LIST}" SILICONCLOUD_PROXY_URL="${SILICONCLOUD_PROXY_URL}" \
    # Spark
    SPARK_API_KEY="${SPARK_API_KEY}" SPARK_MODEL_LIST="${SPARK_MODEL_LIST}" SPARK_PROXY_URL="${SPARK_PROXY_URL}" SPARK_SEARCH_MODE="${SPARK_SEARCH_MODE}" \
    # Stepfun
    STEPFUN_API_KEY="${STEPFUN_API_KEY}" STEPFUN_MODEL_LIST="${STEPFUN_MODEL_LIST}" \
    # Taichu
    TAICHU_API_KEY="${TAICHU_API_KEY}" TAICHU_MODEL_LIST="${TAICHU_MODEL_LIST}" \
    # TogetherAI
    TOGETHERAI_API_KEY="${TOGETHERAI_API_KEY}" TOGETHERAI_MODEL_LIST="${TOGETHERAI_MODEL_LIST}" \
    # Upstage
    UPSTAGE_API_KEY="${UPSTAGE_API_KEY}" UPSTAGE_MODEL_LIST="${UPSTAGE_MODEL_LIST}" \
    # v0 (Vercel)
    V0_API_KEY="${V0_API_KEY}" V0_MODEL_LIST="${V0_MODEL_LIST}" \
    # vLLM
    VLLM_API_KEY="${VLLM_API_KEY}" VLLM_MODEL_LIST="${VLLM_MODEL_LIST}" VLLM_PROXY_URL="${VLLM_PROXY_URL}" \
    # Wenxin
    WENXIN_API_KEY="${WENXIN_API_KEY}" WENXIN_MODEL_LIST="${WENXIN_MODEL_LIST}" \
    # xAI
    XAI_API_KEY="${XAI_API_KEY}" XAI_MODEL_LIST="${XAI_MODEL_LIST}" XAI_PROXY_URL="${XAI_PROXY_URL}" \
    # Xinference
    XINFERENCE_API_KEY="${XINFERENCE_API_KEY}" XINFERENCE_MODEL_LIST="${XINFERENCE_MODEL_LIST}" XINFERENCE_PROXY_URL="${XINFERENCE_PROXY_URL}" \
    # 01.AI
    ZEROONE_API_KEY="${ZEROONE_API_KEY}" ZEROONE_MODEL_LIST="${ZEROONE_MODEL_LIST}" \
    # Zhipu
    ZHIPU_API_KEY="${ZHIPU_API_KEY}" ZHIPU_MODEL_LIST="${ZHIPU_MODEL_LIST}" \
    # Tencent Cloud
    TENCENT_CLOUD_API_KEY="${TENCENT_CLOUD_API_KEY}" TENCENT_CLOUD_MODEL_LIST="${TENCENT_CLOUD_MODEL_LIST}" \
    # Infini-AI
    INFINIAI_API_KEY="${INFINIAI_API_KEY}" INFINIAI_MODEL_LIST="${INFINIAI_MODEL_LIST}"

USER nextjs

EXPOSE 3210/tcp

ENTRYPOINT ["/bin/node"]

CMD ["/app/startServer.js"]